### ISSUE TITLE
Proposal: add `import` hint in provider docs

### ISSUE THREAD

**Issue by yurhasko** [kislerdm/terraform-provider-neon#107]
### Provider Version
0.6.1

So for importing the resources we use `terraform import <resource-import-schema>`. 

Currently, to determine the resource import schame (for example, `neon_role.<role-name>`), it's needed to run `terraform import neon_role.<role-name> <some-value` to get error with the schema: 

```Error: ID of this resource type shall follow the template: {{.ProjectID}}/{{.BranchID}}/{{.Name}}``` 

It would be nice to have `import` example for each resources in docs, like in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#import

**Comment by kislerdm** [comment]
@yurhasko hello! Thank you for the suggestion. A few examples would be helpful indeed. Would you be open to contributing to the provider? I feel that you've got a clear execution path 😀

**Comment by kislerdm** [comment]
@yurhasko Hey! The new version has just been released 🎉  Please check the documentation [enhancement](https://registry.terraform.io/providers/kislerdm/neon/latest/docs/resources/database#import). Thank you for your contribution by bringing the proposal forward! :)

**Comment by kislerdm** [comment]
@yurhasko Hey! The new version has just been released 🎉  Please check the documentation [enhancement](https://registry.terraform.io/providers/kislerdm/neon/latest/docs/resources/database#import). Thank you for your contribution by bringing the proposal forward! :)
