### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by lohrm-stabl** [kislerdm/terraform-provider-neon#112]
Hi there,

the tf provider documentation states the following:

> The number of seconds to retain the point-in-time restore (PITR) backup history for this project.
Default: 7 days, see https://neon.tech/docs/reference/glossary#point-in-time-restore.

https://github.com/kislerdm/terraform-provider-neon/blob/8143094c0929d609591d1a10d237aeb6b6246ce1/internal/provider/resource_project.go#L83

This might be outdated, as the neon docs say:
> By default, Neon retains a history of changes for 1 day across all plans to help avoid unexpected storage costs. You can increase the retention window to 24 hours for [Neon Free Plan](https://neon.tech/docs/introduction/plans#free-plan) users, 7 days for [Launch](https://neon.tech/docs/introduction/plans#launch), 14 days for [Scale](https://neon.tech/docs/introduction/plans#scale), and 30 days for [Business](https://neon.tech/docs/introduction/plans#business) plan users. Keep in mind that this will increase your storage usage and may lead to higher costs, especially if you have many active branches.

https://neon.tech/docs/reference/glossary#point-in-time-restore

**Comment by kislerdm** [comment]
@lohrm-stabl hello Michael, thank you for raising the issue. Would you mind opening PR with the respective change? Thanks!

**Comment by kislerdm** [comment]
@lohrm-stabl hello Michael, thank you for raising the github issue. However, the documentation is consistent with the [default provider's configuration](https://github.com/kislerdm/terraform-provider-neon/blob/8143094c0929d609591d1a10d237aeb6b6246ce1/internal/provider/resource_project.go#L17) for the retention window. No action is required, and I will close the ticket if you don't mind.

**Comment by lohrm-stabl** [comment]
Fair, but the reference to the neon docs makes no sense when it's actually an implementation detail of this repo.
