### ISSUE TITLE
Database data source

### ISSUE THREAD

**Issue by lohrm-stabl** [kislerdm/terraform-provider-neon#115]
It would be nice if there was a data source for the `neon_database` type.

**Comment by lohrm-stabl** [comment]
The attributes would be the same as the `neon_database` type.
The usecase is importing the default database `neondb` which gets created automatically with each project.

**Comment by kislerdm** [comment]
@lohrm-stabl Hey Michael, FYI, the default database is coupled with the `neon_project` resource because it gets provisioned at project provisioning. In other words, if you import provisioned project to tf state, the default database will be imported as well. You could refer to the `neon_project` resource to read its credentials.

**Comment by lohrm-stabl** [comment]
Hey Dmitry,

I see - How would I go about deleting the neondb database using this provider?

Cheers
Michael

**Comment by kislerdm** [comment]
@lohrm-stabl Hey Michael. Could please describe the use case: would you like to delete the default Neon database, or any Neon database? 

Generally speaking, to delete a resource using terraform, regardless of the provider used to provision it, this resource must be managed by terraform first. In other words, one cannot delete resource with terraform if it was not managed by terraform in the first place. One would need to import existing cloud resources to the terraform state and mutate, e.g., delete, them using terraform manifest afterwards.

Regards,
Dmitry

**Comment by lohrm-stabl** [comment]
Hi Dmitry,

yes I'm aware of this. 
I can delete every database very easily when it was defined using a `neon_database ` resource. But since the default database (`neondb`) was not defined using a Terraform resource, I wonder how I would delete that using this provider.

Cheers
Michael

**Comment by kislerdm** [comment]
@lohrm-stabl Hello Michael, could you please share the rationale behind the decision to delete the default database? For context, Neon have decided to provision a database, role and endpoint alongside the project to ease the onboarding, i.e., minimise the effort to provision the infra required to persist the state of your application, so you could focus on delivering your product. In other words, what motivates you to delete the default database for your product?

> I wonder how I would delete that using this provider.

I'd gladly illustrate that - please find two cases below.

## Case 1. Brand new Neon project.

1. Define the Neon project using the following terraform manifest:

```hcl
terraform {
  required_providers {
    neon = {
      source  = "kislerdm/neon"
      version = "0.6.3"
    }
  }
}

provider "neon" {}

resource "neon_project" "this" {
  name = "myproject"
}
```

2. Run `terraform apply -auto-approve`.
3. Define the `neon_database` resource by extending the manifest:

```hcl
terraform {
  required_providers {
    neon = {
      source  = "kislerdm/neon"
      version = "0.6.3"
    }
  }
}

provider "neon" {}

resource "neon_project" "this" {
  name = "myproject"
}

resource "neon_database" "this" {
  name       = "neondb"
  project_id = neon_project.this.id
  branch_id  = neon_project.this.default_branch_id
  owner_name = neon_project.this.database_user
}
```
4.Use the Neon console, or [Neon CLI](https://neon.tech/docs/reference/neon-cli), or [Neon Go SDK](https://github.com/kislerdm/neon-sdk-go) to look up the project ID, branch ID and the database owner name (it's `neondb

**Comment by lohrm-stabl** [comment]
> Neon decided to provision database, role and endpoint alongside the project to ease the onboarding. In other words, what motivates you to delete the default database for your product?

It's great that they provide a default database for new users. However, I provision everything via IaC. And I don't need the `neondb` default database in my project. It just clutters every database ui.
Also, the neon configuration would not match the IaC anymore, because not every database is defined in code.

I agree that this is a minor thing.


Thank you for your the instructions on how to delete the database.
What you are proposing is basically importing the resource and then deleting it.

It's not viable to log into the console and get the default branch id via the url. But this i was able to solve: I iterate through all branches and then filter via `val.id if val.name == "main`.

We also don't have the ability to execute manual terraform commands, as the terraform binary, secrets and state is in a secure, automated environment. Our only input is bunch of terraform files.

What I could do is deploy the IaC along with an import resource every time we create a new project via IaC. However, this would always need a second commit to remove the resource again.
What I get from your explanation is, that there is no way to delete that resource automatically just from writing infrastructure.

I guess what I had in mind was a property for the project `project.this.delete_default_database`

**Comment by kislerdm** [comment]
@lohrm-stabl hey Michael, thanks for clarification. 

Although, I still failed to understand what stops you from using the default database? How the default database provisioned alongside project is worse than the database provisioned explicitly? As far as the database state is concerned, this tf provider allows to create additional roles for databases, or rename the database whether it's the default database, or a custom one.

**Comment by lohrm-stabl** [comment]
We have multiple databases, which are named according to their usecase.
We don't have a usecase that would fit the 'neondb' name.

So renaming the database would work. I'll look into this.

**Comment by lohrm-stabl** [comment]
understandable! thanks anyways

**Comment by kislerdm** [comment]
@lohrm-stabl Thank you! Please consider writing your proposal as RFC - if more users from the community say that their use cases would benefit from introduction of the logic which will delete default db and other resources provision alongside project, I'd be happy to scope it.
