### ISSUE TITLE
Remove outdated warning when creating endpoint with the type "read_only"

### ISSUE THREAD

**Issue by kislerdm** [kislerdm/terraform-provider-neon#122]
Resource: `neon_endpoint`

## Problem

The following warning is displayed when the attribute `type` of the resource `neon_endpoint` is set to "read_only":

```commandline
│ Warning: "read_write" is only supported option yet
│ 
│   with neon_endpoint.this,
│   on main.tf line 25, in resource "neon_endpoint" "this":
│   25:   type                     = "read_only"
```

## Proposed solution

This warning is outdated and should be removed.

**Comment by mickael-carl** [comment]
@kislerdm I believe this can be closed? Looks like it's been fixed in [this commit](https://github.com/kislerdm/terraform-provider-neon/commit/7cd9b83dcdff32011702a152c30948972cb19ac4)? Asking because I was going to take a stab at it otherwise 🙂

**Comment by kislerdm** [comment]
@mickael-carl hey! You're right, it was resolved by the change you mentioned 😀
