### ISSUE TITLE
Default database credentials returned as blank

### ISSUE THREAD

**Issue by domenikk** [kislerdm/terraform-provider-neon#51]
### Terraform Version
```
Terraform v1.5.6
on darwin_arm64
+ provider registry.terraform.io/kislerdm/neon v0.2.2
```

### Provider Version
```
0.2.2
```

### Affected Resource(s)

- neon_project

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    neon = {
      source  = "kislerdm/neon"
      version = "0.2.2"
    }
  }
}

provider "neon" {}

resource "neon_project" "this" {
  name      = var.project_name
  region_id = var.region

  branch {
    name = "master"
    database_name = "neon-test"
    role_name = "admin"
  }
}

output "database_password" {
  value       = neon_project.this.database_password
  sensitive = true
}

output "connection_uri" {
  value       = neon_project.this.connection_uri
  sensitive   = true
}
```

### Debug Output
https://gist.github.com/domenikk/cdba0c29d2fdba4b61375d0a1daa8e5c

### Expected Behavior
The outputs `database_password` and `connection_uri` should have the actual values as shown in Neon console.

### Actual Behavior
Using `terraform output -json` gives this result:
```json
{
  "connection_uri": {
    "sensitive": true,
    "type": "string",
    "value": ""
  },
  "database_password": {
    "sensitive": true,
    "type": "string",
    "value": ""
  }
}
```
Both outputs are empty strings.

### Steps to Reproduce
1. `terraform apply`

**Comment by domenikk** [comment]
@kislerdm Hello again, Dmitry. I'm not sure if this is happening because of the provider or Neon's API. 
But according to their API documentation, this information should be available in `connection_uris` property of `createproject` response: https://api-docs.neon.tech/reference/createproject

**Comment by cassus** [comment]
I have the same issue with 

```terraform
resource "neon_role" "this" {
  project_id = neon_project.this.id
  branch_id  = neon_project.this.default_branch_id
  name       = "role_name"
}
```

`neon_role.this.password` returns empty after I imported it

**Comment by kislerdm** [comment]
@domenikk @cassus Hey folks! Thanks for raising the issue! I'll look into it within a day.

**Comment by amaralc** [comment]
> I have the same issue with 
> 
> 
> 
> ```terraform
> 
> resource "neon_role" "this" {
> 
>   project_id = neon_project.this.id
> 
>   branch_id  = neon_project.this.default_branch_id
> 
>   name       = "role_name"
> 
> }
> 
> ```
> 
> 
> 
> `neon_role.this.password` returns empty after I imported it

Same here.

**Comment by kislerdm** [comment]
@amaralc Hey! Thank you for your feedback! I bet on releasing a fix next week. Although, don't hesitate to open a PR with a fix yourself if you've identified the root cause.

**Comment by amaralc** [comment]
I would love to do so once I get more familiar with Go and with how to develop providers. I am currently a Terraform user but with no Go skills. Hope to change that soon enough though.

**Comment by kislerdm** [comment]
Hey folks! Thank you very much for your feedback and patience! Please update the provider, the issue was resolved. cc: @cassus @domenikk @amaralc

**Comment by amaralc** [comment]
I have just tested it and can confirm it is running as expected. Thanks @kislerdm! By the way, if you have any suggestions on a course or material to get started with Go, let me know. Currently, I work mostly with JS/TS, some bash, and Terraform.

**Comment by cassus** [comment]
I can also confirm, works wonderfully! Thank you @kislerdm !
