### ISSUE TITLE
Creating a project using "aws-us-east-1" region fails

### ISSUE THREAD

**Issue by rshulman-trigo** [kislerdm/terraform-provider-neon#65]
Hi and thanks for developing this!

We are facing an issue creating a new project using the "aws-us-east-1" region. From the [docs](https://neon.tech/docs/introduction/regions) it seems this region is supported, and trying to create a project using the api works, but terraform outputs `region aws-us-east-1 is not supported yet: https://neon.tech/docs/introduction/regions/`.
I think it's related to [this](https://github.com/kislerdm/terraform-provider-neon/blob/master/internal/provider/helper.go#L46) check.

Thank you!

### Terraform Version
Terraform v1.6.6

### Provider Version
provider registry.terraform.io/kislerdm/neon v0.3.1

### Affected Resource(s)
- neon_project

### Terraform Configuration Files
```hcl
resource "neon_project" "this" {
    name      = "this"
    region_id = "aws-us-east-1"
}
```

### Steps to Reproduce
1. `terraform apply`

**Comment by kislerdm** [comment]
Hey @rshulman-trigo! Thank you for opening the issue and for pointing out the route cause! Would you like to implement the fix and contribute to the provider development?

Thanks!
