### ISSUE TITLE
Move provider to be non-internal for pulumi bridged provider

### ISSUE THREAD

**Issue by jcgsville** [kislerdm/terraform-provider-neon#75]
I'm trying to create a Pulumi provider for Neon by creating a bridged terraform provider based on your work here.

I'm using [this boilerplate](https://github.com/pulumi/pulumi-tf-provider-boilerplate). For the tfgen command to work, I need to import your provider package, but because your provider is at `internal/provider/`, `go` will not let me import it.

Is there a reason why the provider is marked as internal? Would there be any harm to moving it to `provider/` so that it can be imported by a Pulumi provider?

Thanks for the work you have put into this provider. It's pretty great :)

**Comment by kislerdm** [comment]
@jcgsville Hey Chandler, thank you for using the provider and for your support! 🙂 

> Is there a reason why the provider is marked as internal? 

Yes, the codebase of the terraform provider is not meant for distribution as Go module. It is a common practice, see the terraform provider's [template](https://github.com/hashicorp/terraform-provider-scaffolding).

The terraform provider uses the [Go SDK](https://github.com/kislerdm/neon-sdk-go) to interact with the Neon via their restful API. If you intend to build a Go app (for example, Pulumi provider) to provision Neon resources, I'd strongly advise you to use the SDK directly without extra complexity layer of the terraform provider. For example, consider following the Pulumi docs which describe how to do so.

I'd kindly decline your request for two reasons:
- It's avoidable modification which goes against terraform template.
- Proposed modification will lead to accidental complexity of dependent software.

Thanks for understanding!

**Comment by jcgsville** [comment]
fair enough :) Thanks for the thoughtful response
