### ISSUE TITLE
As a user, I want to use newly created branch to create a new database

### ISSUE THREAD

**Issue by kislerdm** [kislerdm/terraform-provider-neon#85]
## Problem

It's allowed to create a database using a newly created branch without associated endpoint. It shall be forbidden because endpoint is required to communicate with the database.

## Proposed solution

Every newly created branch will create an RW endpoint.

**Comment by kbumsik** [comment]
Please do not create implicit resource [as mentioned in my comment](https://github.com/kislerdm/terraform-provider-neon/issues/83#issuecomment-1986697328).

How about just writing a documentation to let users to define explicit dependency like this?:

```diff
resource "neon_endpoint" "this" {
  type                     = "read_write"
  ...
}

resource "neon_database" "this" {
  ...

+  depends_on = [neon_endpoint.main]
}
```

**Comment by kislerdm** [comment]
@kbumsik You are right, simplicity is more appropriate in the provider compared to a module where new `branch` and `endpoint` could be abstracted by a single façade.

**Comment by kbumsik** [comment]
Thank you 👍
