### ISSUE TITLE
Add org_id support for the neon_project resource

### ISSUE THREAD

**Issue by yurhasko** [kislerdm/terraform-provider-neon#99]
When creating a Neon project via Terraform/Terragrunt, it's not supported by the provider to specify an **org_id** by the neon_project resource. However, it is supported by the API: https://api-docs.neon.tech/reference/createproject. Due to the absence of this field, it is not possible to create projects in the organization using a personal API key - the project will be created in a personal project.

![image](https://github.com/kislerdm/terraform-provider-neon/assets/103924414/367f8e49-2579-4348-8ea3-8a76a72917cc)

**Comment by suvarnadudam** [comment]
Yes please need the ability to pass org_id in terraform.

**Comment by abilous-ti** [comment]
@kislerdm I am also facing some issues without org_id
Will you be able to included it into next version?

**Comment by kislerdm** [comment]
@yurhasko @suvarnadudam @abilous-ti Hey folks! Thanks for raising the issue. Being able to create a project within an organization makes absolute sense. I will add `organization_id` as an optional attribute of the resource `neon_project` to the provider's release `v0.5.1`.

@neondatabase could you please share best practices to manage projects within an org, i.e., the use of a personal API token does not appear to be the most secure way. Are there system roles, or IAM/authZ concept which you plan on implementing to manage Neon projects in a more secure way? Thanks!

**Comment by abilous-ti** [comment]
@kislerdm Do you have any ETA for release 0.5.1?

**Comment by adi-griever** [comment]
> @yurhasko @suvarnadudam @abilous-ti Hey folks! Thanks for raising the issue. Being able to create a project within an organization makes absolute sense. I will add `organization_id` as an optional attribute of the resource `neon_project` to the provider's release `v0.5.1`.
> 
> @neondatabase could you please share best practices to manage projects within an org, i.e., the use of a personal API token does not appear to be the most secure way. Are there system roles, or IAM/authZ concept which you plan on implementing to manage Neon projects in a more secure way? Thanks!

Currently, you can manage organization projects access with personal API token. We have 2 kinds of roles in an organization: member and admin. Please refer to docs; https://neon.tech/docs/manage/orgs-manage#create-and-delete-projects

When you use the personal API token you will have the permissions by your role in the organization. e.g: If you have a member role in the organization, the API token will have permissions create projects, read projects, but not delete.

In the future we will have API token for organization scope.

**Comment by yurhasko** [comment]
> > @yurhasko @suvarnadudam @abilous-ti Hey folks! Thanks for raising the issue. Being able to create a project within an organization makes absolute sense. I will add `organization_id` as an optional attribute of the resource `neon_project` to the provider's release `v0.5.1`.
> > @neondatabase could you please share best practices to manage projects within an org, i.e., the use of a personal API token does not appear to be the most secure way. Are there system roles, or IAM/authZ concept which you plan on implementing to manage Neon projects in a more secure way? Thanks!
> 
> Currently, you can manage organization projects access with personal API token. We have 2 kinds of roles in an organization: member and admin. Please refer to docs; https://neon.tech/docs/manage/orgs-manage#create-and-delete-projects
> 
> When you use the personal API token you will have the permissions by your role in the organization. e.g: If you have a member role in the organization, the API token will have permissions create projects, read projects, but not delete.
> 
> In the future we will have API token for organization scope.

Currently I cannot specify where to create project in the Terraform resource, because `org_id` field isn't supported in the `neon_project` resource. It means that the Neon project is always created as personal, and there's no option to create it in the Organization. I'm using token create with Admin role (able to perform create/read/delete operations on the projects)

**Comment by adi-griever** [comment]
> Currently I cannot specify where to create project in the Terraform resource, because `org_id` field isn't supported in the `neon_project` resource. It means that the Neon project is always created as personal, and there's no option to create it in the Organization. I'm using token create with Admin role (able to perform create/read/delete operations on the projects)

@yurhasko you can specify where to create a project - https://api-docs.neon.tech/reference/createproject supports `org_id` parameter

**Comment by yurhasko** [comment]
> > Currently I cannot specify where to create project in the Terraform resource, because `org_id` field isn't supported in the `neon_project` resource. It means that the Neon project is always created as personal, and there's no option to create it in the Organization. I'm using token create with Admin role (able to perform create/read/delete operations on the projects)
> 
> @yurhasko you can specify where to create a project - https://api-docs.neon.tech/reference/createproject supports `org_id` parameter

API supports, but Terraform resource `neon_project` of this resource - does not, that's not the same to have it implemented on the Terraform resource level and at the API level. That's why I opened the issue.

**Comment by kislerdm** [comment]
@abilous-ti Hey Andriy! Thanks for your question. I bet on releasing in the second week of October. Sorry for delay - had personal issues with higher priority. Thanks for understanding!

**Comment by kislerdm** [comment]
@abilous-ti, @suvarnadudam, @yurhasko hello folks! The new provider's version has just been released. Thank you very much for your support and patience! ❤️
